PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS customers(
    customer_id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    signup_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);